import {
  CancelledIcon as cancelled,
  CompletedIcon as completed,
  CoursesIcon as courses,
  DashboardIcon as dashboard,
  DownIcon as down,
  LogoIcon as Logo,
  LogoutIcon as logout,
  PendingIcon as pending,
  PinIcon as pin,
  PlusIcon as plus,
  SessionsIcon as sessions,
  SettingsIcon as settings,
  StarIcon as star,
  TeamIcon as team,
  MenuIcon as menu,
  UpIcon as up,
  UploadIcon as Upload,
  WaitingIcon as waiting,
  LightIcon as Light,
  NotificationIcon as Notification,
  SearchIcon as Search,
  DarkLightIcon as DarkLight,
  UpArrowIcon as UpArrow,
  StarIconOrange as StarOrange,
  LogoWebIcon as weblogo,
  DanceTick as tick,
  AnalyticsTag as analytics,
  GymICon as gym,
  Brand1 as brand1,
  Brand2 as brand2,
  Brand3 as brand3,
  Brand4 as brand4,
  Brand5 as brand5,
  BlueTick as bluetick,
  WhiteTick as whitetick,
  ExpertIcon as expert,
  MemberIcon as member,
  CourseManagementIcon as coursemanage,
  AccessibilityIcon as accessibility,
  SchedulingIcon as scheduling,
  PerformanceIcon as performance,
  WhiteLogoWeb as whitelogo,
  RightArrowIcon as rightarrow,
  LoginBg as loginbg,
  LoginBgIcon as login,
  UserIcon as user,
  PasswordIcon as password,
  EyeIcon as eye,
  EmailIcon as email,
  SendEmailIcon as sendEmail,
  LockIcon as lock,
  CheckIcon as check,
  TickCheckIcon as tickicon,
  CameraIcon as camera,
  SignUpDoneSvg as signupdone,
  CloseIcon as close,
  CurrentLocationIcon as currentlocation,
  WeightIcon as weight,
  DollarIcon as dollar,
  DropDownIcon as dropdown,
  VideoIcon as video,
  VideoPlayIcon as play,
  SubscribersIcon as subscribers,
  SubscriptionsIcon as subscription,
  DeleteIcon as deleteicon,
  EditIcon as edit,
  PlusIconBlue as blueplus,
  SubscriptionCheckIcon as subscriptioncheck,
} from "./customIcons";

const AppIcons = {
  dashboard,
  courses,
  team,
  subscribers,
  subscription,
  settings,
  sessions,
  Logo,
  logout,
  down,
  completed,
  cancelled,
  waiting,
  pending,
  up,
  plus,
  pin,
  star,
  menu,
  Upload,
  Light,
  Notification,
  Search,
  DarkLight,
  UpArrow,
  StarOrange,
  weblogo,
  tick,
  analytics,
  brand1,
  brand2,
  brand3,
  brand4,
  brand5,
  gym,
  bluetick,
  whitetick,
  expert,
  member,
  coursemanage,
  accessibility,
  scheduling,
  performance,
  whitelogo,
  rightarrow,
  loginbg,
  login,
  user,
  password,
  eye,
  email,
  sendEmail,
  lock,
  check,
  tickicon,
  camera,
  dollar,
  weight,
  currentlocation,
  signupdone,
  dropdown,
  video,
  play,
  close,
  edit,
  deleteicon,
  blueplus,
  subscriptioncheck,
};

export default AppIcons;
