import {
  CancelledIcon as cancelled,
  CompletedIcon as completed,
  CoursesIcon as courses,
  DashboardIcon as dashboard,
  DownIcon as down,
  LogoIcon as Logo,
  LogoutIcon as logout,
  PendingIcon as pending,
  PinIcon as pin,
  PlusIcon as plus,
  SessionsIcon as sessions,
  SettingsIcon as settings,
  StarIcon as star,
  TeamIcon as team,
  UnionIcon as union,
  UpIcon as up,
  UploadIcon as Upload,
  WaitingIcon as waiting,
  LightIcon as Light,
  NotificationIcon as Notification,
  SearchIcon as Search,
  DarkLightIcon as DarkLight,
  UpArrowIcon as UpArrow,
  StarIconOrange as StarOrange,
} from "./customIcons";

const AppIcons = {
  dashboard,
  courses,
  team,
  settings,
  sessions,
  Logo,
  logout,
  down,
  completed,
  cancelled,
  waiting,
  pending,
  up,
  plus,
  pin,
  star,
  union,
  Upload,
  Light,
  Notification,
  Search,
  DarkLight,
  UpArrow,
  StarOrange,
};

export default AppIcons;
