import fitnessPicture from "../../../public/assets/images/fitnesspicture.png";
font-medium
import AppIcons from "../../../public/assets/icons";
const iconComponents = [
  AppIcons.completed,
  AppIcons.waiting,
  AppIcons.pending,
  AppIcons.cancelled,
  AppIcons.up,
  AppIcons.down,
  AppIcons.union,
  AppIcons.pin,
  AppIcons.star,
];
export const SessionDetails = [
  {
    id: 1,
    picture: fitnessPicture.src,
    title: "Lorem ipsum dolor sit amet,",
    price: "$10.0",
    date: "22 Nov - 30 Nov",
    rating: 15,
    details:
      "High-Intensity Interval Training (HIIT) Cardio, Boost your fitness and torch calories",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ipsum dolor sit amet, consectetur adipiscing elit",
    profilePicture: profilePicture.src,
    Name: "Jane Cooper",
    status: "Active",
    locationIcon: iconComponents[7],
    starIcon: iconComponents[8],
    studio: "Studio A",
    unionIcon: iconComponents[6],
    category: "Fitness Gym",
    edit: "Edit",
    studio: "Studio A",
    startDate: "September 26, 2023",
    endDate: "November 06, 2023",
  },
  {
    id: 2,
    picture: fitnessPicture.src,
    title: "Lorem ipsum dolor sit amet,",
    details:
      "High-Intensity Interval Training (HIIT) Cardio, Boost your fitness and torch calories",
    price: "$10.0",
    date: "22 Nov - 30 Nov",
    rating: 15,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ipsum dolor sit amet, consectetur adipiscing elit",
    profilePicture: profilePicture.src,
    Name: "Jane Cooper",
    status: "Active",
    locationIcon: iconComponents[7],
    starIcon: iconComponents[8],
    studio: "Studio A",
    unionIcon: iconComponents[6],
    category: "Fitness Gym",
    edit: "Edit",
    studio: "Studio A",
    startDate: "September 26, 2023",
    endDate: "November 06, 2023",
  },
  {
    id: 3,
    picture: fitnessPicture.src,
    title: "Lorem ipsum dolor sit amet,",
    details:
      "High-Intensity Interval Training (HIIT) Cardio, Boost your fitness and torch calories",
    price: "$10.0",
    date: "22 Nov - 30 Nov",
    rating: 15,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ipsum dolor sit amet, consectetur adipiscing elit",
    profilePicture: profilePicture.src,
    Name: "Jane Cooper",
    status: "Active",
    locationIcon: iconComponents[7],
    starIcon: iconComponents[8],
    studio: "Studio A",
    unionIcon: iconComponents[6],
    category: "Fitness Gym",
    edit: "Edit",
    studio: "Studio A",
    startDate: "September 26, 2023",
    endDate: "November 06, 2023",
  },
  {
    id: 4,
    picture: fitnessPicture.src,
    title: "Lorem ipsum dolor sit amet,",
    details:
      "High-Intensity Interval Training (HIIT) Cardio, Boost your fitness and torch calories",
    price: "$10.0",
    date: "22 Nov - 30 Nov",
    rating: 15,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ipsum dolor sit amet, consectetur adipiscing elit",
    profilePicture: profilePicture.src,
    Name: "Jane Cooper",
    status: "Active",
    locationIcon: iconComponents[7],
    starIcon: iconComponents[8],
    studio: "Studio A",
    unionIcon: iconComponents[6],
    category: "Fitness Gym",
    edit: "Edit",
    studio: "Studio A",
    startDate: "September 26, 2023",
    endDate: "November 06, 2023",
  },
];
